apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: dual-role
  labels:
    strimzi.io/cluster: {{ .Values.kafka.clusterName }}
    {{- include "stock-pipeline.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  replicas: {{ .Values.kafka.replicas }}
  roles:
    - controller
    - broker
  storage:
    type: persistent-claim
    size: {{ .Values.kafka.storage }}
    deleteClaim: false
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 1000m
---
apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: {{ .Values.kafka.clusterName }}
  labels:
    {{- include "stock-pipeline.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: {{ .Values.kafka.version | quote }}
    metadataVersion: 4.1-IV0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: {{ .Values.kafka.replicas }}
      transaction.state.log.replication.factor: {{ .Values.kafka.replicas }}
      transaction.state.log.min.isr: 2
      default.replication.factor: {{ .Values.kafka.replicas }}
      min.insync.replicas: 2
  entityOperator:
    topicOperator: {}
    userOperator: {}
