apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "stock-pipeline.fullname" . }}-producer
  labels:
    {{- include "stock-pipeline.labels" . | nindent 4 }}
    app.kubernetes.io/component: producer
spec:
  schedule: {{ .Values.producer.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        metadata:
          labels:
            {{- include "stock-pipeline.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: producer
        spec:
          restartPolicy: OnFailure
          containers:
            - name: producer
              image: "{{ .Values.global.registry }}/{{ .Values.producer.image.repository }}:{{ .Values.producer.image.tag }}"
              imagePullPolicy: {{ .Values.global.imagePullPolicy }}
              env:
                - name: KAFKA_BOOTSTRAP_SERVER
                  value: "{{ .Values.kafka.clusterName }}-kafka-bootstrap.{{ .Release.Namespace }}.svc.cluster.local:9092"
              envFrom:
                - secretRef:
                    name: {{ include "stock-pipeline.fullname" . }}-alpha-vantage
              resources:
                {{- toYaml .Values.producer.resources | nindent 16 }}
