apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stock-pipeline.fullname" . }}-alpha-vantage
  labels:
    {{- include "stock-pipeline.labels" . | nindent 4 }}
    app.kubernetes.io/component: producer
type: Opaque
stringData:
  RAPIDAPI_KEY: {{ .Values.producer.rapidapiKey | quote }}
