apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stock-pipeline.fullname" . }}-postgres
  labels:
    {{- include "stock-pipeline.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
