apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: stock-analysis
  namespace: kafka
  labels:
    strimzi.io/cluster: stock-kafka
spec:
  topicName: stock_analysis
  partitions: 6
  replicas: 3
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
